# Generated by Django 6.0.7 on 2026-07-10 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_driver_created_at_driver_updated_at'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('on_run', 'On Run'), ('in_active', 'In Active')], default='available')),
                ('total_cash_collected', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cash_banked_at', models.DateTimeField(blank=True, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.driver')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField(default=0)),
                ('stop_status', models.CharField(choices=[('assigned', 'Assigned'), ('en_route', 'En Route'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='assigned')),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_reason', models.TextField(blank=True, null=True)),
                ('delivery_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryrun')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
