# Generated by Django 6.0.7 on 2026-07-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_deliveryrun_deliverystop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrun',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('completed', 'Completed'), ('cash_banked', 'Cash Banked'), ('cancelled', 'Cancelled')], default='draft'),
        ),
    ]
